# Generated by Django 5.0.7 on 2024-12-30 10:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_user_refferal_by_user_refferal_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerts",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 30, 15, 35, 14, 632780)
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 10, 5, 14, 630780),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 10, 5, 14, 630780),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 15, 35, 14, 633780),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 10, 5, 14, 632780),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 10, 5, 14, 629781),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 10, 5, 14, 629781),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermemberships",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 10, 5, 14, 631799),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermeterreadings",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 30, 15, 35, 14, 632780)
            ),
        ),
        migrations.AlterField(
            model_name="usermeters",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 30, 10, 5, 14, 631799),
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="UserLinked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        default=datetime.datetime(2024, 12, 30, 10, 5, 14, 634780),
                        max_length=100,
                    ),
                ),
                ("status", models.CharField(default="1", max_length=100)),
                (
                    "child_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_child_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_parent_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_linked",
            },
        ),
    ]
