# Generated by Django 5.0.7 on 2024-12-04 09:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_meterpowerconsumption_alter_memberships_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberships",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 4, 9, 14, 57, 489422),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 4, 9, 14, 57, 489422),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 4, 9, 14, 57, 487422),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 4, 9, 14, 57, 487422),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermemberships",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 4, 9, 14, 57, 489422),
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        default=datetime.datetime(2024, 12, 4, 9, 14, 57, 490422),
                        max_length=200,
                    ),
                ),
                ("status", models.CharField(default="1", max_length=200)),
                ("amount", models.CharField(max_length=250)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="UserMeters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("status", models.CharField(default="1", max_length=200)),
                ("location", models.TextField()),
                (
                    "created_at",
                    models.CharField(
                        default=datetime.datetime(2024, 12, 4, 9, 14, 57, 489422),
                        max_length=200,
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usermemberships",
                    ),
                ),
            ],
            options={
                "db_table": "userdevices",
            },
        ),
        migrations.CreateModel(
            name="UserMeterReadings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power", models.CharField(max_length=200)),
                (
                    "datetime",
                    models.CharField(
                        default=datetime.datetime(2024, 12, 4, 9, 14, 57, 490422),
                        max_length=200,
                    ),
                ),
                ("status", models.CharField(default="1", max_length=250)),
                (
                    "meter_id",
                    models.ForeignKey(
                        db_column="meter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usermeters",
                    ),
                ),
            ],
            options={
                "db_table": "usermeterreadings",
            },
        ),
    ]
