# Generated by Django 5.0.7 on 2024-12-05 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_usermeterreadings_amphere_usermeterreadings_volt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meterpowerconsumption",
            name="Amphere",
            field=models.CharField(default="1", max_length=250),
        ),
        migrations.AddField(
            model_name="meterpowerconsumption",
            name="volt",
            field=models.CharField(default="1", max_length=250),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 548683), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 548683), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 550698), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 547672), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 547672), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermemberships",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 549698), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermeterreadings",
            name="datetime",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 549698), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermeters",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 5, 8, 4, 50, 549698), max_length=200
            ),
        ),
    ]
