# Generated by Django 5.0.7 on 2024-12-09 05:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_meterpowerconsumption_amphere_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMAIL_BACKEND", models.CharField(max_length=255)),
                ("EMAIL_HOST", models.CharField(max_length=255)),
                ("EMAIL_PORT", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
                ("EMAIL_HOST_PASSWORD", models.CharField(max_length=255)),
                ("DEFAULT_FROM_EMAIL", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "emailsender",
            },
        ),
        migrations.CreateModel(
            name="WsGroupNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("meterid", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "wsgroupnames",
            },
        ),
        migrations.AlterField(
            model_name="memberships",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 207115),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 207115),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 208606),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 204727),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 204727),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermemberships",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 207115),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermeterreadings",
            name="datetime",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 207115),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermeters",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 5, 28, 16, 207115),
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(default=100, max_length=255)),
                ("currrency", models.CharField(default=100, max_length=255)),
                ("status", models.CharField(default="1", max_length=200)),
                ("comment", models.CharField(max_length=255, null=True)),
                ("image", models.CharField(max_length=255, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
