# Generated by Django 5.0.7 on 2024-12-09 08:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_usermeterreadings_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberships",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 8, 2, 27, 211773), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 8, 2, 27, 211773), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 8, 2, 27, 213775), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 8, 2, 27, 207773), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 8, 2, 27, 207773), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermemberships",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 8, 2, 27, 211773), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermeters",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 9, 8, 2, 27, 211773), max_length=200
            ),
        ),
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=200)),
                ("level", models.CharField(max_length=200)),
                (
                    "meter_id",
                    models.ForeignKey(
                        db_column="meter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usermeters",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
            },
        ),
    ]
