# Generated by Django 5.0.7 on 2025-01-02 06:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_alerts_created_at_alter_memberships_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.CharField(max_length=250)),
                ("plan_period", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(default="1", max_length=200)),
                ("limit", models.CharField(max_length=200)),
                (
                    "updated_at",
                    models.CharField(
                        default=datetime.datetime(2025, 1, 2, 6, 57, 43, 310691),
                        max_length=200,
                    ),
                ),
                (
                    "created_at",
                    models.CharField(
                        default=datetime.datetime(2025, 1, 2, 6, 57, 43, 310691),
                        max_length=200,
                    ),
                ),
            ],
            options={
                "db_table": "packages",
            },
        ),
        migrations.AlterField(
            model_name="alerts",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 2, 12, 27, 43, 312711)
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 310691), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 310691), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 12, 27, 43, 313691),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 312711), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 309602), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 309602), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="userlinked",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 314692), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="usermemberships",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 310691), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermeterreadings",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 2, 12, 27, 43, 311689)
            ),
        ),
        migrations.AlterField(
            model_name="usermeters",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 6, 57, 43, 311689), max_length=200
            ),
        ),
        migrations.CreateModel(
            name="AdminMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="1", max_length=200)),
                (
                    "date",
                    models.CharField(
                        default=datetime.datetime(2025, 1, 2, 6, 57, 43, 311689),
                        max_length=200,
                    ),
                ),
                ("amount", models.CharField(default=0, max_length=250)),
                ("expire_date", models.CharField(max_length=250, null=True)),
                (
                    "plan_id",
                    models.ForeignKey(
                        db_column="plan_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.memberships",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "adminmemberships",
            },
        ),
    ]
