# Generated by Django 5.0.7 on 2025-01-02 08:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_packages_alter_alerts_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminmembership",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 496411), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="adminmembership",
            name="plan_id",
            field=models.ForeignKey(
                db_column="plan_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.packages",
            ),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 2, 14, 28, 30, 496411)
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 495412), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="memberships",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 495412), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="packages",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 495412), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="packages",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 495412), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 14, 28, 30, 498418),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 497424), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 493408), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 493408), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="userlinked",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 498418), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="usermemberships",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 495412), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermeterreadings",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 2, 14, 28, 30, 496411)
            ),
        ),
        migrations.AlterField(
            model_name="usermeters",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2025, 1, 2, 8, 58, 30, 496411), max_length=200
            ),
        ),
    ]
